const express = require('express')
require('./db/connection')
const cors = require('cors')
const applicantRoute = require('./routes/applicant.route')
const articlesRoute = require('./routes/articles.route')
const bookingRoute = require('./routes/booking.route')
const doctorRoute = require('./routes/doctor.route')
const app = express()
app.use(cors())
app.use(express.json())
app.use(applicantRoute)
app.use(articlesRoute)
app.use(bookingRoute)
app.use(doctorRoute)
module.exports = app